version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install --prefix ./frontend
      - npm install

      - pip install --upgrade awscli

  build:
    commands:
      - npm run build --prefix ./frontend

      - aws s3 cp --recursive dist/ s3://WEBSITE_S3_BUCKET_NAME/public/ --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers
      - sed -i -e "s|/assets/|https://$CLOUDFRONT_DISTRIBUTION_DOMAIN_NAME/public/assets/|g" dist/index.html

      - sls deploy -v

artifacts:
  type: zip
  files:
    - template-export.yml
    - template-configuration.json
