service: ${self:custom.service}

custom:
  service: ${file(./config.json):service}
  stage: ${opt:stage, '${file(./config.json):stageTest}'}
  region: ${opt:region, '${file(./config.json):region}'}
  reportsTableName: ${self:service}-${file(./config.json):reportsTableName}-${opt:stage, '${file(./config.json):stage}'}
  reportsTableNameReport: ${self:service}-${file(./config.json):reportsTableNameReport}-${opt:stage, '${file(./config.json):stageTest}'}

provider:
  name: aws
  profile: perfsys
  runtime: nodejs10.x
  stage: ${self:custom.stage}
  region: ${self:custom.region}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - 'dynamodb:*'
      Resource:
        - { "Fn::GetAtt": ["reportsTable", "Arn" ] }
  environment:
    REPORTS_TABLE_NAME_REPORT: ${self:custom.reportsTableNameReport}
#    REPORTS_TABLE_NAME: ${self:custom.reportsTableName}


functions:
  postReport:
    handler: index.handler
    events:
      - http:
          path: '/reports'
          method: POST
          cors: true

  postUserReport:
    handler: index.handler
    events:
      - http:
          path: '/reports/user-report'
          method: POST
          cors: true

  getInfoFromTrello:
    handler: index.handler
    events:
      - http:
          path: /trello/{id}
          method: GET
          cors: true
#  getReports:
#    handler: index.handler
#    events:
#      - http:
#          path: /reports
#          method: GET
#          cors: true

resources:
  Resources:
    reportsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.reportsTableNameReport}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
